# Summary {.unnumbered}

**Background**    
Cardiovascular autonomic dysfunction is a diabetes complication that has been increasingly recognized as a risk factor of cardiovascular disease (CVD). Yet, its clinical utility has remained unclear across stages in the glucose metabolism spectrum.

**Aim**   
This dissertation was aimed at investigating how autonomic dysfunction, assessed by heart rate variability (HRV) and cardiovascular autonomic reflex tests (CARTs), is associated with cardiovascular complications in individuals with normal glucose metabolism, prediabetes, and type 2 diabetes.

**Methods**   
In The Maastricht Study, long-term (24 hours) HRV, together with markers of aortic (carotid-femoral pulse wave velocity) and carotid stiffness (carotid artery distensibility), was quantified in 3,673 individuals with either normal glucose metabolism, prediabetes, or type 2 diabetes. A cross-sectional analysis was conducted to quantify the association between long-term HRV and measures of arterial stiffness across normal glucose metabolism, prediabetes, and type 2 diabetes. In the ADDITION-PRO cohort, HRV over multiple days was quantified in 1,627 individuals at high risk of diabetes and was linked to Danish National Health Registries for outcomes of CVD, heart failure, and all-cause mortality. Time-to-event analysis was applied to quantify the association between multiday and hourly HRV and CVD, heart failure, and all-cause mortality. In The CANCAN Study of 176 individuals with type 2 diabetes visiting outpatient clinics, CARTs were performed, with two or more abnormal values defined as cardiovascular autonomic neuropathy (CAN). A cross-sectional analysis was conducted to evaluate the association between CAN and heart failure indices, with N-terminal pro-B-type natriuretic peptide (NT-proBNP) as the primary index.

**Results**   
Lower long-term HRV was associated with higher aortic and carotid stiffness. These associations were observed across all stages of glucose metabolism and were particularly pronounced in individuals with prediabetes or type 2 diabetes. In a population at high risk of diabetes, lower multiday HRV was linked to a higher incidence of CVD, heart failure, and mortality. Hourly HRV was particularly indicative for CVD in response to the morning period from 6AM to 7AM. In the population with type 2 diabetes in secondary care, CAN was associated with higher heart failure risk by elevated NT-proBNP, even in asymptomatic individuals and those classified as low-to-moderate risk by conventional risk scores.

**Conclusion**    
Autonomic dysfunction was found to be associated with cardiovascular complications across the glycemic continuum. These findings suggest that HRV and CARTs may serve as early, independent markers of cardiovascular risk and become more relevant to individuals with dysglycemia, even before the onset of type 2 diabetes.


\clearpage
\null
\thispagestyle{empty}
\clearpage



# Resume {.unnumbered}

**Baggrund**    
Kardiovaskulær autonom dysfunktion er en diabeteskomplikation, som i stigende grad anerkendes som en risikofaktor for hjertekarsygdomme. På trods af dette er autonom dysfunktions rolle i klinisk praksis ofte overset. Desuden er betydningen af autonom dysfunktion for hjertekarsygdomme på tværs af stadier af glukosemetabolisme endnu ikke klart defineret.

**Formål**    
Denne afhandling har til formål at undersøge, hvordan autonom dysfunktion, målt igennem hjerterytmevariabilitet (HRV) og kardiovaskulære utonome reflekstests (KARTs), er associeret med kardiovaskulære komplikationer hos personer med normal glukosemetabolisme, prædiabetes og type 2-diabetes.

**Metoder**   
I Maastricht studiet blev langvarig HRV (24 timer), sammen med markører for arteriel stivhed i aorta (karotis-femoral pulsbølgehastighed) og halspulsåren (karotisarteriens distensibilitet), målt hos 3.673 personer med enten normal glukosemetabolisme, prædiabetes eller type 2-diabetes. En tværsnitsanalyse blev udført for at kvantificere sammenhængen mellem langvarig HRV og arteriel stivhed på tværs af normal glukosemetabolisme , prædiabetes og type 2-diabetes. I ADDITION-PRO-kohorten blev HRV over flere dage målt hos 1.627 personer med høj risiko for diabetes og blev koblet til de danske nationale sundhedsregistre for udfald af hjertekarsygdom, hjertesvigt og dødelighed af alle årsager. En time-to-event analyse blev anvendt til at analysere sammenhængen mellem flerdages og timebaseret HRV og CVD, hjertesvigt og dødelighed. I CANCAN-studiet af 176 personer med type 2-diabetes, der besøgte ambulatorier, blev KARTs udført, hvor to eller flere unormale værdier blev defineret som kardiovaskulær autonom neuropati (KAN). En tværsnitsanalyse blev udført for at evaluere sammenhængen mellem KAN og hjertesvigtindikatorer, med N-terminal pro-B-type natriuretisk peptide (NT-proBNP) som primær indikator.

**Resultater**    
Lavere langvarig HRV var associeret med højere stivhed i aorta og halspulsåren. Disse sammenhænge blev observeret på tværs af alle stadier af glukosemetabolisme og var særligt udtalte hos personer med prædiabetes eller type 2-diabetes. I en population med høj risiko for diabetes var lavere flerdages HRV forbundet med højere forekomst af hjertekarsygdomme, hjertesvigt og dødelighed. I morgenperioden fra kl. 6 til 7 var timebaseret HRV var særligt indikativ for risiko for hjertekarsygdomme. I populationen med type 2-diabetes var KAN associeret med en øget risiko for hjertesvigt ved forhøjede niveauer af NT-proBNP. Denne sammenhæng blev observeret selv hos personer uden symptomer på hjertesvigt og blandt dem, der var klassificeret som lav- til moderat risiko i en risikoscore.

**Konklusion**    
Autonom dysfunktion er associeret med kardiovaskulære komplikationer på tværs af stadier af glukosemetabolisme. Disse resultater indikerer, at HRV og CARTs kan anvendes som tidlige for øget kardiovaskulær risiko. Autonom dysfunktion er mere relevant for personer med prædiabetes, selv før udviklingen af type 2-diabetes.

\clearpage
\null
\thispagestyle{empty}
\clearpage


