---
title: "Introduction"
---

\newpage

Diabetes mellitus is a growing global health concern, posing pressing challenges for public health systems.[@diabetes2025] As prevalence increases, more individuals are exposed to a higher risk of premature mortality and cardiovascular disease (CVD).[@diabetes2025] At the same time, individuals are living longer with diabetes and therefore endure extended periods under the burden of diabetes-related complications.[@magliano2022] Despite advancements in cardiovascular care, coronary artery disease and heart failure are still often detected at more advanced stages, such as during ischemia, major cardiovascular events, or the onset of symptomatic heart failure in patients with diabetes.[@zamana;@pop-busui2022]

Over recent decades, cardiovascular autonomic dysfunction has repeatedly gained attention as a risk factor for CVD.[@hillebrand2013] Heart rate variability (HRV) is considered a reliable marker for measuring autonomic function, as it reflects the balance between sympathetic and parasympathetic modulation of heart rate intervals.[@taskforceoftheeuropeansocietyofcardiologythenorthamericansocietyofpacingelectrophysiology1996] Despite its recognition as a CVD risk factor, the assessment of cardiovascular autonomic dysfunction has not been implemented in healthcare practice. In diabetes, lower HRV is regarded as an early indicator of cardiovascular autonomic neuropathy (CAN), which is diagnosed using cardiovascular autonomic reflex tests (CARTs).[@eleftheriadou2024] Signs of autonomic dysfunction may already be present in individuals with prediabetes.[@coopmans2020] Despite rising prevalence and increased CVD risk, individuals with prediabetes often remain outside structured treatment pathways.[@rooney2023;@birkenfeld2024] Although diabetes contributes to autonomic dysfunction, it remains unclear at what stage in the diabetes risk spectrum HRV and CARTs become clinically useful for assessing CVD risk.

In the past, measuring HRV needed special instruments like an electrocardiogram. Today, it's easy to track HRV with everyday devices like smartwatches.[@dhingra2023;@bayoumy2021] This increased accessibility allows for continuous monitoring and a better understanding of HRV over extended periods and under various free-living conditions.[@natarajan2020] However, long-term HRV patterns and the relationship between specific diurnal responses and the risk of cardiovascular complications remain less well understood.

The overall aim of this dissertation is to understand how cardiovascular autonomic dysfunction/CAN affects cardiovascular disease risk (i.e. heart failure, stroke, myocardial infarction) and specific subclinical markers of CVD: carotid-femoral pulse wave velocity and carotid artery distensibility in populations covering the whole glycemic continuum, from healthy glucose metabolism to type 2 diabetes.
