project:
  type: book
  output-dir: docs
  
book:
  title: "Cardiovascular autonomic dysfunction impact on cardiovascular complications across glucose metabolism"
  author: "Jonas Rosborg Schaarup"
  date: "2025 06 30"
  date-format: "YYYY"
  chapters:
    - index.qmd
    - pdf1-supervisors.qmd
    # - 0-disclosure.qmd
    # - 0-preface.qmd
    - 0-papers.qmd
    # - 0-abbreviations.qmd
#    - acknowledgements.qmd         # uncomment this line to see acknowledgements in html (will appear twice in pfd)
    - 0-abstract.qmd
    - 1-introduction.qmd
    - 2-background.qmd
    - 3-aim_hypothesis.qmd
    - 4-methods.qmd
    - 5-results.qmd
    - 6-discussion.qmd
    - 7-perspectives.qmd
    - 8-conclusion.qmd
    - references.qmd
  appendices:
    - app1-resources.qmd
    - app2-tools.qmd

bibliography: references.bib
csl: the-lancet.csl

execute:
  freeze: auto
  echo: false # change to false to hide code
  
# format:
#   html:
#     theme: cosmo
#   docx: 
#     toc: true
#     number-sections: true
#     number-depth: 2
#   pdf:
#     documentclass: scrbook
#     classoption:
#      - headsepline=true
#      - open=any
#     keep-tex: true
#     toc-depth: 2
#     toc: false
#     papersize: a4

format:
  html:
    theme: cosmo
    default-image-extension: svg
  docx: 
    prefer-html: true
    toc: true
    number-sections: true
    number-depth: 2
    default-image-extension: tif
    reference-doc: template-doc.docx
  pdf:
    documentclass: scrbook
    default-image-extension: png
    classoption:
     - headsepline=true
     - open=any
    keep-tex: true
    toc-depth: 2
    toc: false
    papersize: a4