# Supervisors and assessment committee {.unnumbered}

#### PhD student:

**Jonas Rosborg Schaarup, Msc in Public Health**\
Department of Public Health, Aarhus University, Denmark

#### Supervisors:

**Professor Daniel R. Witte (main supervisor)**\
Department of Public Health, Aarhus University, Denmark\
Steno Diabetes Center Aarhus, Denmark

**Lasse Bjerg, MD PhD**\
Department of Public Health, Aarhus University, Denmark\
Steno Diabetes Center Aarhus, Denmark

**Signe Toft Andersen, MD PhD**\
Department of Public Health, Aarhus University, Denmark\
Steno Diabetes Center Aarhus, Denmark

**Christian Stevns Hansen, MD PhD**\
Translational Type 2 Diabetes Research\
Steno Diabetes Center Copenhagen, Copenhagen, Denmark



#### Assessment committee:

**Professor Morten Schmidt (chair)**\
Department of Clinical Epidemiology,\
Department of Clinical Medicine, Aarhus University\

**Associate Professor Ilonca Vaartjes**\
University Medical Center Utrecht, Julius Center,\
Department of Epidemiology and Health Economics\

**Cardiologist Peter Godsk Jørgensen**\
Herlev and Gentofte Hospital,   
Capital Region of Denmark